### ISSUE TITLE
How can change default directory in your Stable Diffusion Webui ?

### ISSUE THREAD

**Issue by laichaoyi** [pokewizardSAM/Stable-Diffusion-portable#3]
I changed Checkpoint,lora,.. out of Colab drive but LyCORIS was not supported. Id like to change default directory LyCoris and Controlnet models to google drive. how can you help me ?

**Comment by BlueNecko** [comment]
These things are related to the "stable-diffusion-webui", and any issue regarding this should be asked on their main repository.

 controlnet models are usually saved in extensions folder and as of now there is no such methods I know about it.

**Comment by laichaoyi** [comment]
> These things are related to the "stable-diffusion-webui", and any issue regarding this should be asked on their main repository.
> 
> controlnet models are usually saved in extensions folder and as of now there is no such methods I know about it.

thank you so much !
