### ISSUE TITLE
how to update Automatic1111 webui to 1.4.2 and latest versions ?

### ISSUE THREAD

**Issue by laichaoyi** [pokewizardSAM/Stable-Diffusion-portable#4]
i tried to use your tool to update the WebUI but it didnt work ! still stay in current version 1.4.0. How can i do update it ? i also try to update Controlnet Extension on UI, it didnt work too,

**Comment by BlueNecko** [comment]
As of now the latest updates have major memory leak issues as far I have tested them, and this restrained me from updating the repo and locking it to an older version. 

Even so I have updated the repo so you can update to the latest repo by creating a fresh install and taking a backup afterwards.

**Comment by laichaoyi** [comment]
can i update on old version by running your update tool ? i want to keep my settings and extensions inside my old package.

**Comment by BlueNecko** [comment]
Yo can update without a doubt your settings will remain same.
